/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    ATR001_Doypack_0: THREE.Mesh;
    ATR001_Doypack_0_1: THREE.Mesh;
    ATR001_Doypack_0_2: THREE.Mesh;
  };
  materials: {
    front: THREE.MeshStandardMaterial;
    back: THREE.MeshStandardMaterial;
    filler: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/bag.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="bag"
          position={[0, 0.1, 0]}
          rotation={[0, -1.1, 0]}
          scale={[1.1, 0.8, 1]}
          userData={{ name: "bag" }}
        >
          <mesh
            name="ATR001_Doypack_0"
            castShadow
            receiveShadow
            geometry={nodes.ATR001_Doypack_0.geometry}
            material={materials.front}
          />
          <mesh
            name="ATR001_Doypack_0_1"
            castShadow
            receiveShadow
            geometry={nodes.ATR001_Doypack_0_1.geometry}
            material={materials.back}
          />
          <mesh
            name="ATR001_Doypack_0_2"
            castShadow
            receiveShadow
            geometry={nodes.ATR001_Doypack_0_2.geometry}
            material={materials.filler}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/bag.glb");
